/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    /*  tutorialSidebar: [{
        type: 'autogenerated', dirName: '.'
      }],*/

    // But you can create a sidebar manually
    quickStart: [
        {
            type: "doc",
            id: 'quickstart/readme',
            label: '《潘哥Python教程：快速入门》'
        },
        {
            type: 'link',
            label: '《潘哥Python教程：入门详解》',
            href: '/start'
        },
        {
            type: 'link',
            label: '《潘哥Python教程：进阶实例》',
            href: '/advance/'
        },
        {
            type: 'link',
            label: '《潘哥Python教程：数据结构与算法》',
            href: '/datastructures-and-algorithms/'
        }
    ],
    start: [
        {
            type: 'autogenerated',
            dirName: 'start',
        },
    ],
};

module.exports = sidebars;
